### ISSUE TITLE
Docker container options conflict

### ISSUE THREAD

**Issue by Legion2** [OpenTOSCA/winery#133]
The winery docker image can't be used with volumes and WINERY_REPOSITORY_URL at the same time.

I used the latest https://github.com/OpenTOSCA/opentosca-docker master branch and added the following to the override file:
```
 winery:
    environment:
      WINERY_REPOSITORY_URL: https://github.com/OpenTOSCA/tosca-definitions-public.git
    volumes:
      - /var/opentosca/winery/repository:/var/opentosca/repository
```
This should enable the tosca-definitions-public repository and store it on the host path `/var/opentosca/winery/repository` so it can be modified.
But winery ([docker CMD](https://github.com/OpenTOSCA/winery/blob/ustutt/Dockerfile#L48)) fails: `rm: cannot remove '/var/opentosca/repository': Device or resource busy`, because it tries to delete the mounted directory.

Solutions:
1. don't allow both options at the same time and print a hint if someone tries to use both
2. don't try to delete the mounted directory, only delete the content in the directory
